DROP TABLE IF EXISTS transmissions;
DROP TABLE IF EXISTS responses;
CREATE TABLE transmissions(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command NOT NULL, 
    status NOT NULL DEFAULT 'pending',
);
CREATE TABLE responses(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    response NOT NULL
);
